parseroms chgapl.bin > chgapl.txt
parseroms chgapl2.bin > chgapl2.txt
parseroms chgeuro.xxx > chgeuro.txt
parseroms chggreek.bin > chggreek.txt
parseroms chgkat2.bin > chgkat2.txt
parseroms chgkata.bin > chgkata.txt
parseroms chgmath.xxx > chgmath.txt
parseroms little2.bin > little2.txt
parseroms small.bin > small.txt
parseroms new.bin > new.txt
parseroms chgscrip.bin > chgscrip.txt
